name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许你手动点击按钮触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20

      - name: Install Cloudflare Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          wrangler deploy _worker.js --var AUTH_PASSWORD:"${{ secrets.AUTH_PASSWORD }}" --kv-file-import RENEW_KV="${{ secrets.CF_KV_ID }}"
