name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # 🌟 这里已经升级到最新的 24，消除警告

      - name: Install Cloudflare Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          echo -e "\nkv_namespaces = [{ binding = \"RENEW_KV\", id = \"${{ secrets.CF_KV_ID }}\" }]" >> wrangler.toml
          wrangler deploy _worker.js --var AUTH_PASSWORD:"${{ secrets.AUTH_PASSWORD }}"
